### PR TITLE
User_Employee switch

### PR DESCRIPTION
**Pull request by aoli917**

### CODE REVIEW

**Comment by aoli917** [comment]
@jouhyoung  @chy228930045 -please review

**Comment by jouhyoung** [comment]
@aoli917 
Have you tested to see if you need to run ` python manage.py makemigrations`
In other words, have you tried to see if this actually creates the migrates the DB from current status?

**Comment by aoli917** [comment]
@jouhyoung I did python manage.py makemigrations on my local and I think I published entire branch on my side. We can have hongyu test it as well when he is back

**Comment by jouhyoung** [comment]
ahhh I see what the problem was. The migration files are in gitignore, that's whywe dont see the actual migration files. https://github.com/biu-engineering/biu/pull/27.

**Pull request merged**
