### PR TITLE
antd forms modals, users backend

### PR DESCRIPTION
**Pull request by tstejl**
forms and modals changed to antd, added datepicker
- does not reload page after add/edit/delete yet

added APIs for users and employees

### CODE REVIEW

**Comment by magickaichen** [comment]
Fixing the typography right now

**Comment by magickaichen** [comment]
> @magickaichen
> Are we going to address the bug in this pr?

I have fixed this in my branch, I will create a new PR for this.

**Comment by jouhyoung** [comment]
@tstejl 
Since the other one merged this one has conflict. please rebase and resolve the conflicts.

**Comment by magickaichen** [comment]
Most of the conflicts might be the indent formatting issue, I changed the tab width from 4 to 2 in prettier to comply with the JS format convention.

To change this, simply do this:

In `package.json`:
```diff
"scripts": {
   ...
- "pretty": "prettier --write --tab-width 4 \"src/**/*.js\""
+ "pretty": "prettier --write --tab-width 2 \"src/**/*.js\""
},

**Comment by jouhyoung** [comment]
@magickaichen do you still have issues with this pr? you have requested changes.

**Comment by magickaichen** [comment]
> @magickaichen do you still have issues with this pr? you have requested changes

Not yet tested the code until now, approving right away

**Pull request merged**
